// Style and fonts
import { Inter } from "next/font/google";
import "./globals.css";

// Components
import Layout from "@/components/shared/Layout";
import RainbowKitAndWagmiProvider from "./RainbowKitAndWagmiProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Stratefi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RainbowKitAndWagmiProvider>
          <Layout>
            {children}
          </Layout>
        </RainbowKitAndWagmiProvider>
      </body>
    </html>
  );
}
